name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this bug! Please fill out the sections below.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of what the bug is
      placeholder: Tell us what went wrong
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe what should have happened
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Describe what actually happened
    validations:
      required: true

  - type: textarea
    id: data-sample
    attributes:
      label: Sample Data
      description: If applicable, provide sample data that reproduces the issue
      placeholder: |
        ```json
        { "example": "data" }
        ```
      render: json

  - type: dropdown
    id: format
    attributes:
      label: Data Format
      description: Which data format were you using?
      options:
        - JSON
        - YAML
        - JSONL
        - CSV
        - JSON5
        - Other
    validations:
      required: false

  - type: dropdown
    id: view-mode
    attributes:
      label: View Mode
      description: Which view mode were you using?
      options:
        - Tree View
        - 2D Graph
        - 3D Graph
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Browser and version, OS, screen size, etc.
      placeholder: |
        - Browser: Chrome 120
        - OS: macOS 14.2
        - Screen: 1920x1080
      value: |
        - Browser: 
        - OS: 
        - Screen: 
    validations:
      required: true

  - type: textarea
    id: console-errors
    attributes:
      label: Console Errors
      description: Any errors from browser console (F12)
      placeholder: Paste console errors here
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or information
      placeholder: Add any other relevant information

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have provided all required information
          required: true
