blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/wyattowalsh/datascope/discussions
    about: Ask questions and discuss ideas with the community
  - name: 📚 Documentation
    url: https://datascope.w4w.dev
    about: Read the full documentation
  - name: 🔒 Security Issue
    url: https://github.com/wyattowalsh/datascope/security/advisories/new
    about: Report security vulnerabilities privately
